Feat: 사용자 입력 데이터 저장 기능 추가
bb2002/healix-backend pull request #8
Opened 2024-07-23 08:24 UTC by treasure-sky

사용자 입력 데이터 dto, entity 추가
사용자 입력 데이터 저장 API 추가
사용자 입력 데이터와 연관관계 추가 (user.entitiy.ts)

2024-07-24 01:08 UTC, bb2002 requested changes

2024-07-24 01:08 UTC, bb2002 commented on src/user/dto/user-input.dto.ts
> +export class UserInputDto {
UserInputDto 의 이름 자체가 너무 모호합니다. 이 모듈은 마치 의사처럼 진찰을 하는 기능이니 "examine" 라는 모듈을 따로 만들어 분리하는게 좋겠습니다.

2024-07-24 01:08 UTC, bb2002 commented on src/user/entities/user-input.entity.ts
> +@Entity('user_inputs')
entity 또한 examine 라는 테이블로 하여 명확하게 표현하면 좋겠습니다.

2024-07-24 01:08 UTC, bb2002 commented on src/user/user.controller.ts
> +  @Post(':providerId/inputs')
카톡에서 말씀드린대로 :providerId 로 사용자를 특정하지 않아도 됩니다. 제가 곧 데코레이터랑 파이프를 추가해서 배포해둘 예정이니 그 전까지는 우선 userId (user.eneity.ts 파일의 id 값)를 상수로 고정해서 작업 부탁 드립니다.

2024-07-25 17:03 UTC, treasure-sky commented on src/user/dto/user-input.dto.ts
> +export class UserInputDto {
모듈 분리 완료했습니다!

2024-07-25 17:04 UTC, treasure-sky commented on src/user/entities/user-input.entity.ts
> +@Entity('user_inputs')
모듈 분리한 파일 모두 이름 변경 완료하였습니다!

2024-07-25 17:04 UTC, treasure-sky commented on src/user/user.controller.ts
> +  @Post(':providerId/inputs')
데코레이터, 가드 이용하는 방법으로 수정하였습니다!

2024-07-26 01:50 UTC, bb2002 approved these changes

2024-07-26 01:50 UTC, merged